### ISSUE TITLE
[PLANNED] Classes module (class list)

### ISSUE THREAD

**Issue by MrPiggy105** [OpenTASS/OpenTASS#8]
For @Alvin-Alford if he wants to work on it. I will start.

**Comment by Capta1nT0ad** [comment]
Please stop creating issues. I am 99% sure whatever Project thing you have going to complicate things doesn't require them.

**Comment by Capta1nT0ad** [comment]
I also don't want a million dfferent places to track where PRs are. I *just* want to see the PRs.
